name: RegionAudit
main: net.jwebnet.regionaudit.RegionAudit
version: 1.0

commands:
   rgaudit:
      description: Audit a worldguard region's owners.
      usage: /rgaudit <plotname> [<worldname>]
      permission: regionaudit.audit
      permission-message: You don't have permission