name: RegionsAudit
main: net.jwebnet.regionsaudit.RegionsAudit
version: 1.0

commands:
   rgaudit:
      description: This is a demo command.
      usage: /rgaudit plotname
      permission: regionsaudit.audit
      permission-message: You don't have permission