name: RegionAudit
main: net.jwebnet.regionaudit.RegionAudit
version: 1.0

commands:
   rgaudit:
      description: This is a demo command.
      usage: /rgaudit plotname
      permission: regionaudit.audit
      permission-message: You don't have permission